# FoodTruckieLA Podfile

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

#####################################

target 'ZeroSumGame' do

pod 'ScrollableGraphView'
pod 'Neon'

end

#####################################
# unit testing

#####################################
